# Generated by Django 2.0 on 2018-12-30 19:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseAllot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('disease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Disease')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('total_tablets', models.IntegerField(default=0)),
                ('total_packets', models.IntegerField(default=0)),
                ('total_quantity', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('tablet_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineAllot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('aadhar_id', models.CharField(default=0, max_length=12)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_bill', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='medicineallot',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Patient'),
        ),
        migrations.AddField(
            model_name='diseaseallot',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Patient'),
        ),
    ]
