# Generated by Django 2.0 on 2018-12-31 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20181231_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicineallot',
            old_name='actual_price',
            new_name='pending_price',
        ),
        migrations.RenameField(
            model_name='medicineallot',
            old_name='actual_qty',
            new_name='pending_qty',
        ),
    ]
