# Generated by Django 2.0 on 2019-01-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20181231_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineallot',
            name='alloted_price',
        ),
        migrations.RemoveField(
            model_name='medicineallot',
            name='alloted_qty',
        ),
        migrations.RemoveField(
            model_name='medicineallot',
            name='pending_price',
        ),
        migrations.RemoveField(
            model_name='medicineallot',
            name='pending_qty',
        ),
        migrations.RemoveField(
            model_name='medicineallot',
            name='price',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='total_bill',
        ),
    ]
