# Generated by Django 2.0 on 2019-01-02 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20190102_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date',
        ),
        migrations.AddField(
            model_name='medicine',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
