# Generated by Django 2.0 on 2019-01-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20190102_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='date',
            new_name='med_date',
        ),
    ]
