# Generated by Django 2.0 on 2019-01-02 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20190102_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
