# Generated by Django 2.0 on 2019-01-02 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_patient_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='father_name',
        ),
    ]
