# Generated by Django 2.0 on 2019-01-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_remove_patient_father_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(default='----NA----', max_length=10),
        ),
    ]
